<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <ApplicationIcon>icon.ico</ApplicationIcon>
        <Configurations>Debug;Release;SmallRelease;Tiny</Configurations>
        <Platforms>AnyCPU</Platforms>
        <AssemblyTitle>Show Desktop</AssemblyTitle>
        <Product>Show Desktop</Product>
        <Version>1.0.0</Version>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <DebugType>none</DebugType>
        <AssemblyName>ShowDesktop-v$(Version)</AssemblyName>
        <PublishDir>$(MSBuildProjectDirectory)\bin\</PublishDir>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'SmallRelease'">
        <PublishSingleFile>true</PublishSingleFile>
        <PublishTrimmed>true</PublishTrimmed>
        <SelfContained>true</SelfContained>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <DebugType>none</DebugType>
        <AssemblyName>ShowDesktop-v$(Version)-small</AssemblyName>
        <PublishDir>$(MSBuildProjectDirectory)\bin\</PublishDir>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Tiny'">
        <PublishAot>true</PublishAot>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <DebugType>none</DebugType>
        <AssemblyName>ShowDesktop-v$(Version)-tiny</AssemblyName>
        <PublishDir>$(MSBuildProjectDirectory)\bin\</PublishDir>
    </PropertyGroup>

</Project>
